name: Clever Debug Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Tests
        run: cargo test
      - name: Build
        run: cargo build  --verbose
      - name: Run tests
        run: cargo test --verbose

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Tests
        run: cargo test
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Tests
        run: cargo test
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
